// Generated by rstantools.  Do not edit by hand.

/*
    SedSeqQuant is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SedSeqQuant is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SedSeqQuant.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_SedSeqQuantNoReps_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'SedSeqQuantNoReps', line 18, column 2 to column 34)",
                                                      " (in 'SedSeqQuantNoReps', line 19, column 2 to column 37)",
                                                      " (in 'SedSeqQuantNoReps', line 21, column 2 to column 20)",
                                                      " (in 'SedSeqQuantNoReps', line 25, column 2 to column 87)",
                                                      " (in 'SedSeqQuantNoReps', line 26, column 2 to column 96)",
                                                      " (in 'SedSeqQuantNoReps', line 28, column 2 to column 20)",
                                                      " (in 'SedSeqQuantNoReps', line 31, column 4 to line 32, column 91)",
                                                      " (in 'SedSeqQuantNoReps', line 29, column 20 to line 33, column 3)",
                                                      " (in 'SedSeqQuantNoReps', line 29, column 2 to line 33, column 3)",
                                                      " (in 'SedSeqQuantNoReps', line 3, column 2 to column 20)",
                                                      " (in 'SedSeqQuantNoReps', line 6, column 30 to column 34)",
                                                      " (in 'SedSeqQuantNoReps', line 6, column 2 to column 36)",
                                                      " (in 'SedSeqQuantNoReps', line 7, column 30 to column 34)",
                                                      " (in 'SedSeqQuantNoReps', line 7, column 2 to column 36)",
                                                      " (in 'SedSeqQuantNoReps', line 8, column 30 to column 34)",
                                                      " (in 'SedSeqQuantNoReps', line 8, column 2 to column 36)",
                                                      " (in 'SedSeqQuantNoReps', line 10, column 2 to column 36)",
                                                      " (in 'SedSeqQuantNoReps', line 11, column 2 to column 34)",
                                                      " (in 'SedSeqQuantNoReps', line 12, column 2 to column 39)",
                                                      " (in 'SedSeqQuantNoReps', line 13, column 2 to column 37)"};
#include <stan_meta_header.hpp>
class model_SedSeqQuantNoReps final : public model_base_crtp<model_SedSeqQuantNoReps> {
private:
  int NRNA;
  std::vector<int> tot_obs_counts;
  std::vector<int> sup_obs_counts;
  std::vector<int> pel_obs_counts;
  double mixing_factor_sup_guess_mean;
  double mixing_factor_sup_guess_sd;
  double mixing_factor_pellet_guess_mean;
  double mixing_factor_pellet_guess_sd;
 
public:
  ~model_SedSeqQuantNoReps() { }
  
  inline std::string model_name() const final { return "model_SedSeqQuantNoReps"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_SedSeqQuantNoReps(stan::io::var_context& context__,
                          unsigned int random_seed__ = 0,
                          std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_SedSeqQuantNoReps_namespace::model_SedSeqQuantNoReps";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 10;
      context__.validate_dims("data initialization","NRNA","int",
          context__.to_vec());
      NRNA = std::numeric_limits<int>::min();
      
      current_statement__ = 10;
      NRNA = context__.vals_i("NRNA")[(1 - 1)];
      current_statement__ = 10;
      current_statement__ = 10;
      check_greater_or_equal(function__, "NRNA", NRNA, 1);
      current_statement__ = 11;
      validate_non_negative_index("tot_obs_counts", "NRNA", NRNA);
      current_statement__ = 12;
      context__.validate_dims("data initialization","tot_obs_counts","int",
          context__.to_vec(NRNA));
      tot_obs_counts = std::vector<int>(NRNA, std::numeric_limits<int>::min());
      
      current_statement__ = 12;
      assign(tot_obs_counts, nil_index_list(),
        context__.vals_i("tot_obs_counts"),
        "assigning variable tot_obs_counts");
      current_statement__ = 12;
      for (int sym1__ = 1; sym1__ <= NRNA; ++sym1__) {
        current_statement__ = 12;
        current_statement__ = 12;
        check_greater_or_equal(function__, "tot_obs_counts[sym1__]",
                               tot_obs_counts[(sym1__ - 1)], 0);}
      current_statement__ = 13;
      validate_non_negative_index("sup_obs_counts", "NRNA", NRNA);
      current_statement__ = 14;
      context__.validate_dims("data initialization","sup_obs_counts","int",
          context__.to_vec(NRNA));
      sup_obs_counts = std::vector<int>(NRNA, std::numeric_limits<int>::min());
      
      current_statement__ = 14;
      assign(sup_obs_counts, nil_index_list(),
        context__.vals_i("sup_obs_counts"),
        "assigning variable sup_obs_counts");
      current_statement__ = 14;
      for (int sym1__ = 1; sym1__ <= NRNA; ++sym1__) {
        current_statement__ = 14;
        current_statement__ = 14;
        check_greater_or_equal(function__, "sup_obs_counts[sym1__]",
                               sup_obs_counts[(sym1__ - 1)], 0);}
      current_statement__ = 15;
      validate_non_negative_index("pel_obs_counts", "NRNA", NRNA);
      current_statement__ = 16;
      context__.validate_dims("data initialization","pel_obs_counts","int",
          context__.to_vec(NRNA));
      pel_obs_counts = std::vector<int>(NRNA, std::numeric_limits<int>::min());
      
      current_statement__ = 16;
      assign(pel_obs_counts, nil_index_list(),
        context__.vals_i("pel_obs_counts"),
        "assigning variable pel_obs_counts");
      current_statement__ = 16;
      for (int sym1__ = 1; sym1__ <= NRNA; ++sym1__) {
        current_statement__ = 16;
        current_statement__ = 16;
        check_greater_or_equal(function__, "pel_obs_counts[sym1__]",
                               pel_obs_counts[(sym1__ - 1)], 0);}
      current_statement__ = 17;
      context__.validate_dims("data initialization",
          "mixing_factor_sup_guess_mean","double",context__.to_vec());
      mixing_factor_sup_guess_mean = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 17;
      mixing_factor_sup_guess_mean = context__.vals_r("mixing_factor_sup_guess_mean")[
          (1 - 1)];
      current_statement__ = 18;
      context__.validate_dims("data initialization",
          "mixing_factor_sup_guess_sd","double",context__.to_vec());
      mixing_factor_sup_guess_sd = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 18;
      mixing_factor_sup_guess_sd = context__.vals_r("mixing_factor_sup_guess_sd")[
          (1 - 1)];
      current_statement__ = 19;
      context__.validate_dims("data initialization",
          "mixing_factor_pellet_guess_mean","double",context__.to_vec());
      mixing_factor_pellet_guess_mean = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 19;
      mixing_factor_pellet_guess_mean = context__.vals_r("mixing_factor_pellet_guess_mean")[
          (1 - 1)];
      current_statement__ = 20;
      context__.validate_dims("data initialization",
          "mixing_factor_pellet_guess_sd","double",context__.to_vec());
      mixing_factor_pellet_guess_sd = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 20;
      mixing_factor_pellet_guess_sd = context__.vals_r("mixing_factor_pellet_guess_sd")[
          (1 - 1)];
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_SedSeqQuantNoReps_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      local_scalar_t__ mixing_factor_sup;
      mixing_factor_sup = DUMMY_VAR__;
      
      current_statement__ = 1;
      mixing_factor_sup = in__.scalar();
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        mixing_factor_sup = stan::math::lb_constrain(mixing_factor_sup, 0,
                              lp__);
      } else {
        current_statement__ = 1;
        mixing_factor_sup = stan::math::lb_constrain(mixing_factor_sup, 0);
      }
      local_scalar_t__ mixing_factor_pellet;
      mixing_factor_pellet = DUMMY_VAR__;
      
      current_statement__ = 2;
      mixing_factor_pellet = in__.scalar();
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        mixing_factor_pellet = stan::math::lb_constrain(mixing_factor_pellet,
                                 0, lp__);
      } else {
        current_statement__ = 2;
        mixing_factor_pellet = stan::math::lb_constrain(mixing_factor_pellet,
                                 0);
      }
      local_scalar_t__ phi;
      phi = DUMMY_VAR__;
      
      current_statement__ = 3;
      phi = in__.scalar();
      current_statement__ = 3;
      if (jacobian__) {
        current_statement__ = 3;
        phi = stan::math::lb_constrain(phi, 0, lp__);
      } else {
        current_statement__ = 3;
        phi = stan::math::lb_constrain(phi, 0);
      }
      {
        current_statement__ = 4;
        lp_accum__.add(
          normal_lpdf<propto__>(mixing_factor_sup,
            mixing_factor_sup_guess_mean, mixing_factor_sup_guess_sd));
        current_statement__ = 5;
        lp_accum__.add(
          normal_lpdf<propto__>(mixing_factor_pellet,
            mixing_factor_pellet_guess_mean, mixing_factor_pellet_guess_sd));
        current_statement__ = 6;
        lp_accum__.add(cauchy_lpdf<propto__>(phi, 0, 3));
        current_statement__ = 9;
        for (int idx = 1; idx <= NRNA; ++idx) {
          current_statement__ = 7;
          lp_accum__.add(
            neg_binomial_2_lpmf<propto__>(tot_obs_counts[(idx - 1)],
              ((sup_obs_counts[(idx - 1)] / mixing_factor_sup) +
                (pel_obs_counts[(idx - 1)] / mixing_factor_pellet)), phi));}
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_SedSeqQuantNoReps_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      double mixing_factor_sup;
      mixing_factor_sup = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      mixing_factor_sup = in__.scalar();
      current_statement__ = 1;
      mixing_factor_sup = stan::math::lb_constrain(mixing_factor_sup, 0);
      double mixing_factor_pellet;
      mixing_factor_pellet = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      mixing_factor_pellet = in__.scalar();
      current_statement__ = 2;
      mixing_factor_pellet = stan::math::lb_constrain(mixing_factor_pellet, 0);
      double phi;
      phi = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      phi = in__.scalar();
      current_statement__ = 3;
      phi = stan::math::lb_constrain(phi, 0);
      vars__.emplace_back(mixing_factor_sup);
      vars__.emplace_back(mixing_factor_pellet);
      vars__.emplace_back(phi);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double mixing_factor_sup;
      mixing_factor_sup = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      mixing_factor_sup = context__.vals_r("mixing_factor_sup")[(1 - 1)];
      double mixing_factor_sup_free__;
      mixing_factor_sup_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      mixing_factor_sup_free__ = stan::math::lb_free(mixing_factor_sup, 0);
      double mixing_factor_pellet;
      mixing_factor_pellet = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      mixing_factor_pellet = context__.vals_r("mixing_factor_pellet")[
          (1 - 1)];
      double mixing_factor_pellet_free__;
      mixing_factor_pellet_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      mixing_factor_pellet_free__ = stan::math::lb_free(mixing_factor_pellet,
                                      0);
      double phi;
      phi = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      phi = context__.vals_r("phi")[(1 - 1)];
      double phi_free__;
      phi_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      phi_free__ = stan::math::lb_free(phi, 0);
      vars__.emplace_back(mixing_factor_sup_free__);
      vars__.emplace_back(mixing_factor_pellet_free__);
      vars__.emplace_back(phi_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("mixing_factor_sup");
    names__.emplace_back("mixing_factor_pellet");
    names__.emplace_back("phi");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "mixing_factor_sup");
    param_names__.emplace_back(std::string() + "mixing_factor_pellet");
    param_names__.emplace_back(std::string() + "phi");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "mixing_factor_sup");
    param_names__.emplace_back(std::string() + "mixing_factor_pellet");
    param_names__.emplace_back(std::string() + "phi");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"mixing_factor_sup\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mixing_factor_pellet\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"phi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"mixing_factor_sup\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mixing_factor_pellet\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"phi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_SedSeqQuantNoReps_namespace::model_SedSeqQuantNoReps;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_SedSeqQuantNoReps_namespace::profiles__;
}
#endif
#endif
