#' Simulated pSup Data
#'
#' A simulated dataset of pSups generated from actual total counts
#' Started with a dataset of 7 reps of RNA-seq total counts for unstressed yeast cells
#' Random pSups were generated for each transcript
#' Random mixing parameters were generated for each rep
#' Noise on the supernatant and pellet counts were generated by applying
#' negative binomial noise to the total counts
#' @format ## `generated_count_data`
#' A count matrix for input into load_counts
"generated_count_data"


#' Samplesheet for simulated pSup Data
#'
#' Samplesheet for simulated dataset of pSups
#' @format ## `generated_data_samplesheet`
#' A samplesheet tsv for input into load_counts
"generated_data_samplesheet"

#' Simulated pSup Data parameters
#'
#' A simulated dataset of pSups generated from actual total counts
#' Started with a dataset of 7 reps of RNA-seq total counts for unstressed yeast cells
#' Random pSups were generated for each transcript
#' Random mixing parameters were generated for each rep
#' Noise on the supernatant and pellet counts were generated by applying
#' negative binomial noise to the total counts
#' @format ## `generated_data_input_pSups`
#' Parameters used to generated the simulated counts
#' Compare modeled counts with pSup_generated or pSup.withnoise.mean
"generated_data_input_pSups"
